var chapterNumber = 8;
var chapter=[
    
    
    {data:{
        "mode" : "cCoach",
        "section":"Glycolysis",
        "video":'https://mediaplayer.pearsoncmg.com/assets/_embed.video-container/secs-microbio-glycolysis',
        "transcript":'In this Concept Coach we will learn about cellular respiration. Cellular respiration is a collection of reactions that extract energy from foods. Energy is extracted by oxidizing nutrients like glucose—that is, by removing electrons from the sugar. The extracted energy is transferred to the chemical bonds of ATP, the cell’s “molecular money.”<br><br>Cellular respiration can be thought of as a two-stage process: an electron-harvesting phase and an electron-depositing phase. <br>Electrons are harvested from glucose by glycolysis, an intermediate step, and the Krebs cycle.<br><br>NADH and FADH<sub>2</sub> collect the electrons and carry them to the electron transport chain.<br><br>The electron transport chain can be thought of as a deposit phase because when electrons are dropped off to this pathway they fuel the production of large quantities of ATP.<br><br>Let’s zoom in on the phases of cellular respiration, starting with glycolysis.<br><br>In the first pathway of cellular respiration, glycolysis, a six-carbon molecule of glucose, is split in half, producing two three-carbon molecules called pyruvic acid. <br><br>Think of glycolysis as breaking a stick in half. Just as it takes energy to break the stick,it takes energy to break glucose. Also, none of the original carbons in glucose are lost in glycolysis, just as none of the original stick is lost--it is just in a different form.<br><br>You may have heard the old phrase that it takes money to make money, meaning it takes an initial investment to lead to a greater profit. The same is true in cells.<br><br>Cellular respiration will ultimately lead to a <i>much</i> greater ATP payoff than what cells invest to start the process.<br><br>In the first stage of glycolysis, the investment stage, two ATP molecules are invested to help split glucose into two molecules of glyceraldehyde 3-phosphate.<br><br>After glucose is split, the reactions of the second stage of glycolysis, or the payoff stage, harvest electrons from the remnants of glucose. Electron harvesting is accomplished using an electron carrier called NAD<sup>+</sup>. You can think of NAD<sup>+</sup> as an electron taxi that oxidizes, or takes away, electrons from organic intermediates––in this case, glyceraldehyde 3-phosphate. <br><br>When NAD<sup>+</sup> picks up electrons it is chemically reduced to NADH. The two NADHs made in glycolysis are like coupons that can be cashed in later for more ATP.<br><br>In addition to the two NADH molecules made in glycolysis, we also end up with four ATP molecules that were made by substrate-level phosphorylation.<br><br>However, because we used two ATP in the investment stage of glycolysis, our actual profit is only two ATPs. Finally, we wrap up glycolysis when two pyruvic acid molecules are made. These can be further oxidized--that is, stripped of electrons--to make even more ATP.<br><br>'        
    }},
    
    
    {data:{
        "mode" : "cCoach",
        "section":"Intermediate Step & Krebs Cycle",
        "video":'https://mediaplayer.pearsoncmg.com/assets/_embed.video-container/secs-microbio-intermediate-step',
        "transcript":'The two pyruvic acid molecules made in glycolysis enter the intermediate step where they each lose a carbon in the form of carbon dioxide.<br><br>This reaction is accompanied by a redox reaction in which pyruvic acid is oxidized and NAD<sup>+</sup> is reduced to NADH.<br><br>The intermediate step leaves us with two molecules of acetyl-CoA, a two-carbon compound that continues into the Krebs cycle for further energy harvesting.<br><br>In the Krebs cycle, acetyl-CoA is further broken down by decarboxylation reactions--reactions that remove carbon as CO<sub>2</sub> and redox reactions, which make more of our electron taxis, NADH and FADH<sub>2</sub>. The Krebs cycle will run twice for each glucose that originally entered cellular respiration.<br><br>By the end of the Krebs cycle, all of the carbons that were originally in glucose are released as carbon dioxide.<br><br>Although the Krebs cycle makes 2 molecules of ATP by substrate-level phosphorylation, the main energy benefit of the cycle is to produce a total of 6 more NADH and 2 FADH<sub>2</sub> through redox reactions.<br>'
        
    }},

    {data:{
        "mode" : "cCoach",
        "section":"Electron Transport Chain",
        "video":'https://mediaplayer.pearsoncmg.com/assets/_embed.video-container/secs-microbio-electron-transport-chain',
        "transcript":'Let’s now focus on the last pathway of cellular respiration, the electron transport chain.<br><br>The electrons harvested in glycolysis, the intermediate step, and the Krebs cycle are taken to the electron transport chain by the electron taxis NADH and FADH<sub>2</sub>.<br><br>There the deposited electrons drive the production of 34 ATP and water. This is the maximum amount of ATP that can be made in aerobic respiration.<br><br>NADH and FADH<sub>2</sub> drop off their electron passengers to the electron transport chain much like students passing notes in class. The membrane-bound proteins that make up the electron transport chain pass the deposited electrons from one protein in the chain to another.<br><br>Zooming in on the electron transport chain, we see that electrons are passed from electron carrier to electron carrier using redox reactions. In aerobic cellular respiration, the final electron acceptor is oxygen while in anaerobic cellular respiration an inorganic substance other than oxygen, such as nitrate or sulfate, serves as the final electron acceptor.<br><br>The electron transport chain makes most of the ATP in cellular respiration. It does so using a process called chemiosmosis.<br><br>Chemiosmosis relies on the energy that is released as electrons are passed along the electron transport chain. <br><br>This energy is used to pump protons across a membrane, creating a gradient.<br><br>In bacteria, which lack mitochondria, the electrons are pumped into the space outside the bacterial cell.<br><br>In eukaryotic cells, the protons are pumped into the inner membrane space of mitochondria.<br><br>Eventually the protons that were pumped across the membrane will flow back to where they came from by flowing through ATP synthase. <br><br>Taking a closer look at ATP synthase, we can see the protons flow from areas of high concentration to areas of low concentration through the transmembrane protein ATP synthase. This action is the actual chemiosmosis event.<br><br>Chemiosmosis is similar to water running through a hydroelectric dam.<br><br>When protons move through ATP synthase they cause the protein to spin––just as water flowing though a dam spins a turbine. This spinning motion provides the energy that bonds a phosphate to ADP to make ATP. This method of making ATP is called oxidative phosphorylation.<br><br>In summary, cellular respiration includes glycolysis, the intermediate step, the Krebs cycle, and the electron transport chain. The coordinated actions of these pathways make a net profit of 38 ATP per glucose molecule.<br><br>'
    }}
]




